openapi: 3.1.0
info:
  title: Simple API with External Refs
  version: 1.0.0
paths:
  /users:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './external/external1.yaml#/components/schemas/User' # same repo, subfolder
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/your-user/other-specs/main/external2.yaml#/components/schemas/UserResponse' # cross-repo
components:
  schemas:
    Context:
      type: object
      properties:
        domain:
          type: string
      required:
        - domain
